### ISSUE TITLE
[BUG]: workflow tests fail on main

### ISSUE THREAD

**Issue by dabrahams** [SomeRandomiOSDev/CBORCoding#28]
### Expected Behavior

clean run of `scripts/workflowtests.sh`

### Actual Behavior

See attached failure log
[cbor-workflowtests-log.txt](https://github.com/SomeRandomiOSDev/CBORCoding/files/13330112/cbor-workflowtests-log.txt)

### Steps To Reproduce

1.  `scripts/workflowtests.sh`

### Project Version

e12b478

### The OS/Variant where this issue occurs.

- [ ] iOS
- [X] macOS
- [ ] tvOS
- [ ] watchOS
- [ ] Mac Catalyst
- [ ] Other (Please specify in "Additional Context" section)

### The version of Xcode that was used when this issue appeared.

15.0.1

### What was the environment in which the issue appeared?

- [X] CBORCoding.xcodeproj
- [ ] Package.swift
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [ ] Other (Please specify in "Additional Context" section)

**Comment by SomeRandomiOSDev** [comment]
Looks like it's an issue with the minimum versions not being up to date with what Xcode supports. I'll push some changes to update the minimum supported versions so that everything builds as expected

**Comment by SomeRandomiOSDev** [comment]
Fixed 🙂
