### ISSUE TITLE
[BUG]: `swift test` is failing on Linux

### ISSUE THREAD

**Issue by dabrahams** [SomeRandomiOSDev/CBORCoding#29]
### Expected Behavior

pass

### Actual Behavior

Failure log is [here](https://github.com/SomeRandomiOSDev/CBORCoding/actions/runs/6826206647/job/18565649407)

### Steps To Reproduce

Let tests run in CI or run them on your own Linux box

### Project Version

e12b478

### The OS/Variant where this issue occurs.

- [ ] iOS
- [ ] macOS
- [ ] tvOS
- [ ] watchOS
- [ ] Mac Catalyst
- [X] Other (Please specify in "Additional Context" section)

### The version of Xcode that was used when this issue appeared.

n/a

### What was the environment in which the issue appeared?

- [ ] CBORCoding.xcodeproj
- [ ] Package.swift
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [X] Other (Please specify in "Additional Context" section)

### Additional Context

In CI, on Linux

**Comment by dabrahams** [comment]
Reproduces in a [local `.devcontainer`](https://github.com/SomeRandomiOSDev/CBORCoding/files/13339736/dot-devcontainer.zip) on my mac:

```
/workspaces/CBORCoding/Tests/CBORCodingTests/CBORParserTests.swift:176: error: CBORParserTests.testAppendixASimpleExamples : XCTAssertEqual failed: ("-inf") is not equal to ("0.0") -
```

Looking at the code that does this decoding, I don't really understand it but the use of unsafe operations makes me at least a little suspicious.

**Comment by SomeRandomiOSDev** [comment]
Fixed in the Half library and updated this to use the fixed version
